services:
    Ernadoo\MondialRelayBundle\SoapClient:
        arguments: ['@Symfony\Component\Stopwatch\Stopwatch', '', '']
        autowire: true
        
    MondialRelay\ApiClient:
        class: MondialRelay\ApiClient
        arguments: ['@Ernadoo\MondialRelayBundle\SoapClient', '', '']
        autowire: true

    Ernadoo\MondialRelayBundle\DataCollector\MondialRelayDataCollector:
        class: Ernadoo\MondialRelayBundle\DataCollector\MondialRelayDataCollector
        arguments: ['@Ernadoo\MondialRelayBundle\SoapClient']
        tags:
            - { name: data_collector, template: '@ErnadooMondialRelay/Collector/mondialrelay.html.twig', id: "ernadoo.mondialrelay" }

    Ernadoo\MondialRelayBundle\Twig\MondialRelayTwigExtension:
        class: Ernadoo\MondialRelayBundle\Twig\MondialRelayTwigExtension
        arguments: ['%ernadoo_mondial_relay.customer_code%']
        tags: [twig.extension]