services:
    Ernadoo\MondialRelay\MondialRelayWebAPI:
        class: Ernadoo\MondialRelay\MondialRelayWebAPI
        arguments: ['@Symfony\Component\Stopwatch\Stopwatch', '', '', '']
        autowire: true

    Ernadoo\MondialRelayBundle\DataCollector\MondialRelayDataCollector:
        class: Ernadoo\MondialRelayBundle\DataCollector\MondialRelayDataCollector
        arguments: ['@Ernadoo\MondialRelay\MondialRelayWebAPI']
        public: false
        tags:
            - { name: data_collector, template: '@ErnadooMondialRelay/Collector/mondialrelay.html.twig', id: "app.request_collector" }

    Ernadoo\MondialRelayBundle\Twig\MondialRelayTwigExtension:
        class: Ernadoo\MondialRelayBundle\Twig\MondialRelayTwigExtension
        arguments: ['%ernadoo_mondial_relay.customer_code%']
        tags: [twig.extension]